In [1]:
import requests
from bs4 import BeautifulSoup # pakiet do parsowania, żeby Python był świadom struktury znaczników
import re
import numpy as np
import pandas as pd

In [10]:
def Scrape_US_temperatures(print_results = True):
    
    'returns "temps" dataframe with historical average low and high temperatures for each month and each US state'
    
    url = 'https://www.usclimatedata.com'
    answer = requests.get(url)
    website = answer.text
    soup = BeautifulSoup(website, 'html.parser')
    global temps
    temps = []
    states_names = []
    
    for link in soup.findAll('a', {'class': 'province'}):
        
        url_state = (f"{url}{link.get('href')}")
        answer_state = requests.get(url_state)
        website_state = answer_state.text
        soup_state = BeautifulSoup(website_state, 'html.parser')
        if print_results == True:
            print(url_state)
        
        my_table_top = []
        my_table_bottom = []
        td_top = []
        td_bottom = []
        temps_high = []
        temps_low = []        

        my_table_top = soup_state.find('table')
        td_top = my_table_top.findAll('td')

        my_table_bottom = soup_state.find('table', {'class':'climate_table_margin_top'})
        td_bottom = my_table_bottom.findAll('td')


        for row in range(8, 14):
    #         print(int(re.findall('\d+', str(td_top[row]))[0]))
            temps_low.append(int(re.findall('\d+', str(td_top[row]))[0]))
#         print(temps_low)

        for row in range(1, 7):
    #         print(int(re.findall('\d+', str(td_top[row]))[0]))
            temps_high.append(int(re.findall('\d+', str(td_top[row]))[0]))
#         print(temps_high)

        for row in range(8, 14):
    #         print(int(re.findall('\d+', str(td_bottom[row]))[0]))
            temps_low.append(int(re.findall('\d+', str(td_bottom[row]))[0]))
        if print_results == True:
            print(temps_low)
        
        for row in range(1, 7):
    #         print(int(re.findall('\d+', str(td_bottom[row]))[0]))
            temps_high.append(int(re.findall('\d+', str(td_bottom[row]))[0]))
        if print_results == True:
            print(temps_high)


        temps.append(temps_low)
        temps.append(temps_high)
        
        states_names.append(f'''{re.findall('^.+climate/(.+)/united.+', f'{url}{link.get("href")}')[0].capitalize()}_low_t''')
        states_names.append(f'''{re.findall('^.+climate/(.+)/united.+', f'{url}{link.get("href")}')[0].capitalize()}_high_t''')
        
        if print_results == True:
            print(' ')

    temps = pd.DataFrame(temps).T
    temps.columns = states_names
    
    return temps

In [11]:
Scrape_US_temperatures(False)

,Alabama_low_t,Alabama_high_t,Kentucky_low_t,Kentucky_high_t,North-dakota_low_t,North-dakota_high_t,Alaska_low_t,Alaska_high_t,Louisiana_low_t,Louisiana_high_t,...,New-york_low_t,New-york_high_t,Wisconsin_low_t,Wisconsin_high_t,Kansas_low_t,Kansas_high_t,North-carolina_low_t,North-carolina_high_t,Wyoming_low_t,Wyoming_high_t
0,36,57,21,40,2,23,11,23,45,62,...,26,39,16,29,20,40,30,51,18,40
1,39,62,23,45,8,28,14,27,48,65,...,29,42,19,33,24,45,33,55,19,40
2,45,70,31,55,19,40,19,34,53,72,...,35,50,28,42,33,56,39,63,24,47
3,52,77,39,66,31,57,29,44,60,78,...,44,60,37,54,44,67,47,72,31,55
4,61,84,49,75,43,68,40,56,68,85,...,55,71,47,65,54,76,56,79,40,65
5,68,90,59,83,52,77,48,63,74,89,...,64,79,57,75,64,85,65,86,49,75
6,71,92,63,87,57,85,52,65,75,91,...,70,85,64,80,68,89,68,89,56,83
7,71,92,62,86,56,83,50,64,75,91,...,69,83,63,78,66,89,67,87,54,81
8,65,87,55,79,45,72,42,55,72,87,...,61,76,55,71,56,80,60,81,45,72
9,53,78,42,68,32,58,29,40,63,80,...,50,65,43,59,45,68,49,72,34,59
10,44,69,34,55,19,40,17,28,53,72,...,41,54,32,46,33,55,39,62,24,47
11,37,60,26,44,6,26,13,25,47,64,...,32,44,20,33,22,42,32,53,17,38

In [4]:
temps

,Alabama_low_t,Alabama_high_t,Kentucky_low_t,Kentucky_high_t,North-dakota_low_t,North-dakota_high_t,Alaska_low_t,Alaska_high_t,Louisiana_low_t,Louisiana_high_t,...,New-york_low_t,New-york_high_t,Wisconsin_low_t,Wisconsin_high_t,Kansas_low_t,Kansas_high_t,North-carolina_low_t,North-carolina_high_t,Wyoming_low_t,Wyoming_high_t
0,36,57,21,40,2,23,11,23,45,62,...,26,39,16,29,20,40,30,51,18,40
1,39,62,23,45,8,28,14,27,48,65,...,29,42,19,33,24,45,33,55,19,40
2,45,70,31,55,19,40,19,34,53,72,...,35,50,28,42,33,56,39,63,24,47
3,52,77,39,66,31,57,29,44,60,78,...,44,60,37,54,44,67,47,72,31,55
4,61,84,49,75,43,68,40,56,68,85,...,55,71,47,65,54,76,56,79,40,65
5,68,90,59,83,52,77,48,63,74,89,...,64,79,57,75,64,85,65,86,49,75
6,71,92,63,87,57,85,52,65,75,91,...,70,85,64,80,68,89,68,89,56,83
7,71,92,62,86,56,83,50,64,75,91,...,69,83,63,78,66,89,67,87,54,81
8,65,87,55,79,45,72,42,55,72,87,...,61,76,55,71,56,80,60,81,45,72
9,53,78,42,68,32,58,29,40,63,80,...,50,65,43,59,45,68,49,72,34,59
10,44,69,34,55,19,40,17,28,53,72,...,41,54,32,46,33,55,39,62,24,47
11,37,60,26,44,6,26,13,25,47,64,...,32,44,20,33,22,42,32,53,17,38