In [2]:
import requests
from bs4 import BeautifulSoup # pakiet do parsowania, żeby Python był świadom struktury znaczników
import re
import numpy as np
import pandas as pd

In [45]:
url = 'https://www.usclimatedata.com'
answer = requests.get(url)
answer

In [13]:
answer.status_code   # 200 oznacza, że odpowiedź ze strony nastąpiła bez problemów

200

In [14]:
website = answer.text

In [16]:
# website

'\n\r\n<!doctype html>\n<html lang="en">\n<head>\n<link rel="stylesheet" href="/css/style.css">\n<link rel="stylesheet" href="/css/menu-min.css">\n<link rel="stylesheet" href="/css/custom-theme/jquery-ui-1.8.22.custom.css">\n<link rel="stylesheet" href="/css/tabs_theme/jquery-ui-1.10.3.custom.css" /><link rel="stylesheet" type="text/css" href="/css/jchartfx.css" />\n<meta charset="utf-8">\n<meta name="copyright" content="US Climate Data">\n<meta name="author" content="US Climate Data">\n<meta name="Distribution" content="Global">\n<meta name="google-site-verification" content="YZ0ca6l60VXXsJQ6xmJlgIGawHVFuXmAJcVFQ4hVnkY" />\n<meta name="robots" content="index, follow"><meta name="description" content="The climate in the United States. Information regarding the temperature, precipitation, and sunshine for more than 5000 cities and locations in the United States. The climate in Washington, District of Columbia. " />\n<meta name="keywords" content="climate, data, average, climate chart, winter, cities, location, rainfall, temperature, sunshine hours,  precipitation, historical, yearly, climograph, summer, Washington, District of Columbia, Arlington, United States" />\n<title>Climate - United States - Monthly averages</title>\n<script type="text/javascript" src="/javascript/jquery-1.10.2.min.js"></script>\t\n<script type="text/javascript" src="/javascript/jquery-ui-1.10.3-custom-min.js"></script>\n<script async type="text/javascript" src="/javascript/jquery.ui.autocomplete.html.js"></script>\n<script async type="text/javascript" src="/javascript/formdefaults.js"></script>\n<script async type="text/javascript" src="/javascript/search.js"></script>\n<script async type="text/javascript" src="/javascript/jquery.cookies.js"></script>\n\n<script type="text/javascript" src="/javascript/jchartfx/jchartfx.system.js"></script>\n<script type="text/javascript" src="/javascript/jchartfx/jchartfx.coreBasic.js"></script>\n<!-- <script type="text/javascript" src="http://www.geoplugin.net/extras/cookielaw.js"></script> -->\n<script type="text/javascript" src="/javascript/loadScript.js"></script>\n<script type="text/javascript">\t\njQuery(document).ready(function($)\n{\t\n\t$(function() { $( "#tabs" ).tabs();});\t\n\t$(\'.system\').html("°F");\n\t$(\'.precip_system\').html("inch");\n\t/* Change Climate Data when click on the Celcius or Fahrenheit button */\n\t$(".btn").click(function() \n\t{\t\n\t\t\n\t\tvar system = this.id;\t\t\t\n\t\n\t\t$.ajax({ \t\t\n\t\t\turl: "/php/scale-system.php", \n    \t\ttype: \'POST\',\n\t\t\tdataType: "json",\n    \t\tdata: {\t\n\t\t\t\tweather_id: \'usdc0001\',\n\t\t\t\ttype: system,\n\t\t\t\taltitude: \'4\'\t\t\t\t\t\n\t\t\t},\n    \t\tsuccess: function(data) \n\t\t\t{\t\t\t\t\t\t\n\t\t\t\t$(\'#climate_table\').html(data.climate_table);\n\t\t\t\t$(\'.system\').html(data.temperature_system);\n\t\t\t\t$(\'.precip_system\').html(data.precipitation_system);\t\t\t\t\n\t\t\t\t$(\'#climate_totals\').html(data.climate_totals);\t\t\t\n\t\t\t}\n\t\t});\n\t});\n});\n</script>\n<script type="text/javascript" language="javascript">\njQuery(document).ready(function($)\n{\n\t//Reload graph with metric or american value\n\t$(".btn").click(function() \n\t{\t\n\t\t$(\'#ChartDiv\').html("");\n\t\tvar system_graph = this.id;\t\t\n\t\t\n\t\t$.ajax({ \t\t\n\t\t\turl: "/php/graph.php", \n    \t\ttype: \'POST\',\n\t\t\tdataType: "json",\n    \t\tdata: {\t\n\t\t\t\tweather_id: \'usdc0001\',\t\t\t\t\n\t\t\t\ttype: system_graph,\t\t\t\t\t\t\t\t\n\t\t\t},\n    \t\tsuccess: function(data) \n\t\t\t{\t\t\t\t\t\t\n\t\t\t\tvar min_temp_graph = data.min_temp_graph;\t\t\t\t\t\t\t\t\t\t\n\t\t\t\tvar max_temp_graph = data.max_temp_graph;\t\t\t\t\n\t\t\t\tvar the_data = data.new_data;\n\t\t\t\tvar precipitation_step = data.precipitation_step;\t\t\t\t\t\t\t\n\t\t\t\tvar precipitation_max = data.precipitation_max;\t\t\t\t\n\t\t\t\tvar system_standards = data.system_standards;\t\t\t\t\t\n\t\t\t\tvar system_name = data.system_name;\t\t\t\t\t\n\t\t\t\tvar steppy = data.step;\t\t\t\t\t\t\t\n\t\t\t\tloadChart(min_temp_graph,max_temp_graph,the_data,precipitation_max,precipitation_step,steppy,system_standards,system_name);\t\t\t\t\n\t\t\t}\n\t\t});\n\t\t\n\t});\t\t\n\tvar min_temp_graph = 20;\n\tvar max_temp_graph = 90;\t\n\tvar the_data = \'[{"Month": "Jan", "Low":27, "High":42, "Precipitation": 3.03},{"Month": "Feb", "Low":28, "High":44, "Precipitation": 2.48},{"Month": "Mar", "Low":35, "High":53, "Precipitation": 3.23},{"Month": "Apr", "Low":44, "High":64, "Precipitation": 3.15},{"Month": "May", "Low":54, "High":75, "Precipitation": 4.13},{"Month": "Jun", "Low":63, "High":83, "Precipitation": 3.23},{"Month": "Jul", "Low":68, "High":87, "Precipitation": 4.13},{"Month": "Aug", "Low":66, "High":84, "Precipitation": 4.88},{"Month": "Sep", "Low":59, "High":78, "Precipitation": 3.82},{"Month": "Oct", "Low":48, "High":67, "Precipitation": 3.07},{"Month": "Nov", "Low":38, "High":55, "Precipitation": 2.83},{"Month": "Dec", "Low":29, "High":45, "Precipitation": 2.8}]\';\t\t\n\tvar precipitation_max = 5;\n\tvar precipitation_step = 1;\n\n\tvar steppy = 20;\t\n\tvar system_standards = "°F";\n\tvar system_name = "american";\n    var chart1;\n\t\n\tloadChart(min_temp_graph,max_temp_graph,the_data,precipitation_max,precipitation_step,steppy,system_standards,system_name);\n    function loadChart(min_temp_graph,max_temp_graph,the_data,precipitation_max,precipitation_step,steppy,system_standards,system_name)\n    {\n            chart1 = new cfx.Chart();\n            chart1.getData().setSeries(3);\n\t\t\tchart1.setBackground(null);\n\t\t\t\n\t\t\t/* Temperature */\t\t\t\t\t\n           \tchart1.getAxisY().setMin(min_temp_graph); //Low\n           \tchart1.getAxisY().setMax(max_temp_graph); // High\n\t\t   \tchart1.getAxisY().setStep(10);\n\t\t\tif(system_name == "american")\n\t\t\t{\n\t\t\t\tchart1.getAxisY().getLabels().setItem(0,"20°F");chart1.getAxisY().getLabels().setItem(20,"40°F");chart1.getAxisY().getLabels().setItem(40,"60°F");chart1.getAxisY().getLabels().setItem(60,"80°F");\t\t\t}\n\t\t\tif(system_name == "metric")\n\t\t\t{\n\t\t\t\tchart1.getAxisY().getLabels().setItem(0,"-10°C");chart1.getAxisY().getLabels().setItem(10,"0°C");chart1.getAxisY().getLabels().setItem(20,"10°C");chart1.getAxisY().getLabels().setItem(30,"20°C");chart1.getAxisY().getLabels().setItem(40,"30°C");chart1.getAxisY().getLabels().setItem(50,"40°C");\t\t\t}\n\t\t\t/* Precipitation */\t\t\t\n\t\t\tchart1.getAxisY2().setMin(0); \n            chart1.getAxisY2().setMax(precipitation_max);\n\t\t\tchart1.getAxisY2().setStep(precipitation_step);\t\n\t\t\tif(system_name == "american")\n\t\t\t{\t\n\t\t\t  chart1.getAxisY2().getLabels().setItem(0,"0inch");chart1.getAxisY2().getLabels().setItem(1,"1inch");chart1.getAxisY2().getLabels().setItem(2,"2inch");chart1.getAxisY2().getLabels().setItem(3,"3inch");chart1.getAxisY2().getLabels().setItem(4,"4inch");chart1.getAxisY2().getLabels().setItem(5,"5inch");\t\t\t}\t\n\t\t\tif(system_name == "metric")\n\t\t\t{\t\n\t\t\t  chart1.getAxisY2().getLabels().setItem(0,"0mm");chart1.getAxisY2().getLabels().setItem(20,"20mm");chart1.getAxisY2().getLabels().setItem(40,"40mm");chart1.getAxisY2().getLabels().setItem(60,"60mm");chart1.getAxisY2().getLabels().setItem(80,"80mm");chart1.getAxisY2().getLabels().setItem(100,"100mm");chart1.getAxisY2().getLabels().setItem(120,"120mm");chart1.getAxisY2().getLabels().setItem(140,"140mm");\t\t\t}\t\t\t\t\t\t\t\t\n            var series1 = chart1.getSeries().getItem(0);\n            var series2 = chart1.getSeries().getItem(1);\n\t\t\tvar series3 = chart1.getSeries().getItem(2);\n\t\t\t\n\t\t\t/* Second Y-Axis - Precipitation */\n\t\t\tseries3.setAxisY(chart1.getAxisY2());\n            series1.setGallery(cfx.Gallery.Lines);\n\t\t\tseries2.setGallery(cfx.Gallery.Lines);\n            series3.setGallery(cfx.Gallery.Bar);\n\t\t\tchart1.getLegendBox().setDock(cfx.DockArea.Bottom);\n\t\t\tchart1.getAllSeries().setMarkerShape(cfx.MarkerShape.None);\n\t\t\t/* Climate Data */\t\t\t\n            var data = JSON.parse(the_data);\n\n            chart1.setDataSource(data);\n            var divHolder = document.getElementById(\'ChartDiv\');\n        \tchart1.create(divHolder);\n      }\n}); \n</script>\n<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>\n<script>\n     (adsbygoogle = window.adsbygoogle || []).push({\n          google_ad_client: "ca-pub-9519329606981542",\n          enable_page_level_ads: true\n     });\n</script>\n</head>\n<body>\n<script>\n  (function(i,s,o,g,r,a,m){i[\'GoogleAnalyticsObject\']=r;i[r]=i[r]||function(){\n  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),\n  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)\n  })(window,document,\'script\',\'https://www.google-analytics.com/analytics.js\',\'ga\');\n\n  ga(\'create\', \'UA-2018376-13\', \'auto\');\n  ga(\'send\', \'pageview\');\n\n</script><!-- Start header **** -->\n<header>\n\t<!-- Wrap -->\n\t<div class="wrap">\n\t\t<!-- Logo & Slogan -->\t\t\n  \t\t<div id="logo">\n        \t<!-- Slogan -->\n\t\t\t<div id="slogan">\n\t\t\t\t<h1>Temperature - Precipitation - Sunshine - Snowfall</h1>\n\t\t\t</div>\n            <!-- End slogan -->\n    \t</div>\n        <!-- End Logo & Slogan -->\n        <!-- Social media -->\n        <div id="sociale-media">\n\t\t\t<div id=scale>\n  <span class="sociale-media-text">US Climate Data on </span>\n  <a title=\'US Climate Data on Facebook\' href=\'https://www.facebook.com/yourweatherservice\'>\n\t  <img src=\'/images/icons/facebook.png\' width=\'16\' height=\'16\' alt=\'US Climate Data on Facebook\' />\n  </a>\n  <a title=\'US Climate Data on Twitter\' href=\'https://twitter.com/usclimatedata\'>\n\t  <img src=\'/images/icons/twitter.png\' width=\'16\' height=\'16\' alt=\'US Climate Data on Twitter\' />\n  </a>\n</div>    \n        </div>\n    </div>\n    <!-- End wrap -->\n</header>\n<!-- End header **** -->\n<!-- Navigation **** -->\n<nav>\n\t<div class="wrapper_menu_full menu_light_theme">\n\t<!-- Begin menu wrapper -->\n    <div class="menu menu_blue">\n    \t<!-- Begin menu -->\n        <div class="wrap">\n        <ul class="menu_whole_width">\n        \t<!-- Home -->\n\t\t\t<li class="nodrop"><a title="Climate" href="http://www.usclimatedata.com">Home</a></li>\n            <!-- United States -->\n            <li class="nodrop"><a title="Climate United States" href="/climate/united-states/us">United States</a></li>\n                        <!-- World -->  \n            <!--        \n            <li><a title="Climate of the World" href="#" class="drop">World</a>\n            -->\n           \t\t<!-- Subitems -->\n                <!--\n            \t<div class="dropdown_1column">\n                    <div class="col_1 firstcolumn">                    \n                        <ul class="levels">                        \n                            <li><a title="Climate Africa" href="/normals/africa/2">Africa</a></li>                            \n                            <li><a title="Climate Asia" href="/normals/asia/142">Asia</a></li>\n                            <li><a title="Climate Europe" href="/normals/europe/150">Europe</a></li>\n                            <li><a title="Climate North-Central America" href="/normals/north-central-america/19">North-Central America</a></li>\n                            <li><a title="Climate South America" href="/normals/south-america/20">South America</a></li>\n                            <li><a title="Climate Oceania" href="/normals/oceania/9">Oceania</a></li>\n                        </ul> \n                    </div>\n                </div>\n                -->\n            </li>            \n            <div id="search">\n            \t\n         \t\t<input value="Enter a location" class="form-text" id="searchfield"> \n           \t\t\n           </div> \n           <!-- My location -->             \n          </ul> \n       </div>\t\t\n    </div>\n </div></nav>\n<!-- End navigation **** -->\n<!-- Content **** -->\n<div id="content">\n\t<!-- Wrap -->    \t\n\t<div class="wrap">\n\t\t<!-- Climate -->\n\t\t<div id="climate">        \t \n        \t<!-- Site Tabs -->\n\t\t\t<div class="site_tabs">\n            \t<!-- Tabs -->\n\t\t\t\t<div id="tabs">\n\t\t\t\t<ul>\n                    <li><a class="summary" href="#summary">Monthly</a></li>\n                    <!-- Breadcrumbs -->\t\t\t              \n                    <p class="breadcrumbs">You are here: <a href="\\"  title="Home">Home</a></p>\n                    <!-- end Breadcrumbs -->\n\t\t        </ul>\n                <!-- Summary -->    \n\t\t       \t<div id="summary">\n                  <!-- left_column --> \t\t\t\t\t\t\n                  <div class="left_column">\n                      <h1 class="h1_title">Climate Washington - District of Columbia</h1>\n                      <span class="choose_system"><a rel="nofollow" class="btn" id="metric" href="#">°C</a> | <a rel="nofollow" class="btn" id="american" href="#">°F</a></span>                      <!-- Climate table --> \n                      <div id="climate_table">\n                          <table><tr><th>&nbsp;</th><th class="climate_table_data_td">Jan</th><th class="climate_table_data_td">Feb</th><th class="climate_table_data_td">Mar</th><th class="climate_table_data_td">Apr</th><th class="climate_table_data_td">May</th><th class="climate_table_data_td">Jun</th></tr><tr><td class="climate_table_info">Average high in <span class=system></span>:</td><td class="align_right temperature_red">42</td><td class="align_right temperature_red">44</td><td class="align_right temperature_red">53</td><td class="align_right temperature_red">64</td><td class="align_right temperature_red">75</td><td class="align_right temperature_red">83</td></tr><tr><td class="climate_table_info">Average low in <span class=system></span>:</td><td class="align_right temperature_blue">27</td><td class="align_right temperature_blue">28</td><td class="align_right temperature_blue">35</td><td class="align_right temperature_blue">44</td><td class="align_right temperature_blue">54</td><td class="align_right temperature_blue">63</td></tr><tr><td class="climate_table_info">Av. precipitation in <span class=precip_system></span>:</td><td class="align_right">3.03</td><td class="align_right">2.48</td><td class="align_right">3.23</td><td class="align_right">3.15</td><td class="align_right">4.13</td><td class="align_right">3.23</td></tr><tr><td class="climate_table_info">Days with precipitation:</td><td class="align_right">11</td><td class="align_right">8</td><td class="align_right">12</td><td class="align_right">10</td><td class="align_right">12</td><td class="align_right">9</td></tr><tr><td class="climate_table_info">Hours of sunshine:</td><td class="align_right">76</td><td class="align_right">97</td><td class="align_right">135</td><td class="align_right">182</td><td class="align_right">221</td><td class="align_right">214</td></tr></table><table class="climate_table_margin_top"><tr><th>&nbsp;</th><th class="climate_table_data_td">Jul</th><th class="climate_table_data_td">Aug</th><th class="climate_table_data_td">Sep</th><th class="climate_table_data_td">Oct</th><th class="climate_table_data_td">Nov</th><th class="climate_table_data_td">Dec</th></tr><tr><td class="climate_table_info">Average high in <span class=system></span>:</td><td class="align_right temperature_red">87</td><td class="align_right temperature_red">84</td><td class="align_right temperature_red">78</td><td class="align_right temperature_red">67</td><td class="align_right temperature_red">55</td><td class="align_right temperature_red">45</td></tr><tr><td class="climate_table_info">Average low in <span class=system></span>:</td><td class="align_right temperature_blue">68</td><td class="align_right temperature_blue">66</td><td class="align_right temperature_blue">59</td><td class="align_right temperature_blue">48</td><td class="align_right temperature_blue">38</td><td class="align_right temperature_blue">29</td></tr><tr><td class="climate_table_info">Av. precipitation in <span class=precip_system></span>:</td><td class="align_right">4.13</td><td class="align_right">4.88</td><td class="align_right">3.82</td><td class="align_right">3.07</td><td class="align_right">2.83</td><td class="align_right">2.8</td></tr><tr><td class="climate_table_info">Days with precipitation:</td><td class="align_right">10</td><td class="align_right">10</td><td class="align_right">8</td><td class="align_right">8</td><td class="align_right">8</td><td class="align_right">9</td></tr><tr><td class="climate_table_info">Hours of sunshine:</td><td class="align_right">226</td><td class="align_right">186</td><td class="align_right">170</td><td class="align_right">123</td><td class="align_right">87</td><td class="align_right">66</td></tr></table>                      </div>\n                      <!-- end Climate table -->\n                      <!-- Google Ad Content Left -->  \n             \t\t  <div id="google-ad-content_left">             \t\t\n                 \t\t<p style=padding-top:4px>\n<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>\n<!-- Weernetwerk2012Content -->\n<ins class="adsbygoogle"\n     style="display:inline-block;width:468px;height:60px"\n     data-ad-client="ca-pub-9519329606981542"\n     data-ad-slot="4359484752"></ins>\n<script>\n(adsbygoogle = window.adsbygoogle || []).push({});\n</script>\n</p>\n                \t</div>                    \n                      <!-- Climograph -->\n                      <div id="climograph">\n                          <h2>\n                              Washington Climate Graph                               - District of Columbia Climate Chart                          </h2>\n                         <div id="ChartDiv" style="width:430px;height:340px"></div>\n                      </div>\n                      <!-- end Climograph -->   \n                      <h2>Totals and averages</h2>\n                      <!-- Climate Totals -->\n                      <div id="climate_totals">\n                          <table><tr><td class="totals_left_column">Annual high temperature:</td><td class="temperature_red totals_right_column">64.8°F</td></tr><tr><td>Annual low temperature:</td><td class="temperature_blue">46.6°F</td></tr><tr><td>Average temperature:</td><td>55.7°F</td></tr><tr><td>Average annual precipitation - rainfall:</td><td>40.78 inch</td></tr><tr><td>Days per year with precipitation - rainfall:</td><td>115 days</td></tr><tr><td>Annual hours of sunshine:</td><td>1783 hours</td></tr><tr><td>Av. annual snowfall:</td><td>-</td></tr></table>                      </div>\n                      <!-- Normal period -->\n                      <div id="extra_info">\n                       \t<p>Climate data for Washington, DC - 22202 - 1961-1990 normals - weather</p>                     \n                      </div>\n                      <!-- end Normal period -->  \n                      <!-- Legend -->\n                      <div id="legend">\n                      \t   <p>Jan: January, Feb: February, Mar: March, Apr: April, May: May, Jun: June, Jul: July, Aug: August, Sep: September, Oct: October, Nov: November, Dec: December</p>\n                      </div>\n                      <!-- end Legend -->\n                        <!-- Share -->\n                       <div id="buttons">        \n\t\t<div class="addthis_inline_share_toolbox"></div>\n\t <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-4e3ca9c46c176e26"></script> \n</div>                                   <!-- end Share -->\n              </div>\n              <!-- end left_column --> \n              <!-- end right_column -->     \n              <div class="right_column">\n                  <h3>Select a state by name</h3>\n                                    <table><tbody><tr><td class="thr

In [17]:
soup = BeautifulSoup(website, 'html.parser')
print(soup.prettify())

<!DOCTYPE html>
<html lang="en">
 <head>
  <link href="/css/style.css" rel="stylesheet"/>
  <link href="/css/menu-min.css" rel="stylesheet"/>
  <link href="/css/custom-theme/jquery-ui-1.8.22.custom.css" rel="stylesheet"/>
  <link href="/css/tabs_theme/jquery-ui-1.10.3.custom.css" rel="stylesheet">
   <link href="/css/jchartfx.css" rel="stylesheet" type="text/css">
    <meta charset="utf-8"/>
    <meta content="US Climate Data" name="copyright"/>
    <meta content="US Climate Data" name="author"/>
    <meta content="Global" name="Distribution"/>
    <meta content="YZ0ca6l60VXXsJQ6xmJlgIGawHVFuXmAJcVFQ4hVnkY" name="google-site-verification">
     <meta content="index, follow" name="robots"/>
     <meta content="The climate in the United States. Information regarding the temperature, precipitation, and sunshine for more than 5000 cities and locations in the United States. The climate in Washington, District of Columbia. " name="description">
      <meta content="climate, data, average, climate chart, winter, cities, location, rainfall, temperature, sunshine hours,  precipitation, historical, yearly, climograph, summer, Washington, District of Columbia, Arlington, United States" name="keywords">
       <title>
        Climate - United States - Monthly averages
       </title>
       <script src="/javascript/jquery-1.10.2.min.js" type="text/javascript">
       </script>
       <script src="/javascript/jquery-ui-1.10.3-custom-min.js" type="text/javascript">
       </script>
       <script async="" src="/javascript/jquery.ui.autocomplete.html.js" type="text/javascript">
       </script>
       <script async="" src="/javascript/formdefaults.js" type="text/javascript">
       </script>
       <script async="" src="/javascript/search.js" type="text/javascript">
       </script>
       <script async="" src="/javascript/jquery.cookies.js" type="text/javascript">
       </script>
       <script src="/javascript/jchartfx/jchartfx.system.js" type="text/javascript">
       </script>
       <script src="/javascript/jchartfx/jchartfx.coreBasic.js" type="text/javascript">
       </script>
       <!-- <script type="text/javascript" src="http://www.geoplugin.net/extras/cookielaw.js"></script> -->
       <script src="/javascript/loadScript.js" type="text/javascript">
       </script>
       <script type="text/javascript">
        jQuery(document).ready(function($)
{
	$(function() { $( "#tabs" ).tabs();});
	$('.system').html("°F");
	$('.precip_system').html("inch");
	/* Change Climate Data when click on the Celcius or Fahrenheit button */
	$(".btn").click(function()
	{

		var system = this.id;

		$.ajax({
			url: "/php/scale-system.php",
    		type: 'POST',
			dataType: "json",
    		data: {
				weather_id: 'usdc0001',
				type: system,
				altitude: '4'
			},
    		success: function(data)
			{
				$('#climate_table').html(data.climate_table);
				$('.system').html(data.temperature_system);
				$('.precip_system').html(data.precipitation_system);
				$('#climate_totals').html(data.climate_totals);
			}
		});
	});
});
       </script>
       <script language="javascript" type="text/javascript">
        jQuery(document).ready(function($)
{
	//Reload graph with metric or american value
	$(".btn").click(function()
	{
		$('#ChartDiv').html("");
		var system_graph = this.id;

		$.ajax({
			url: "/php/graph.php",
    		type: 'POST',
			dataType: "json",
    		data: {
				weather_id: 'usdc0001',
				type: system_graph,
			},
    		success: function(data)
			{
				var min_temp_graph = data.min_temp_graph;
				var max_temp_graph = data.max_temp_graph;
				var the_data = data.new_data;
				var precipitation_step = data.precipitation_step;
				var precipitation_max = data.precipitation_max;
				var system_standards = data.system_standards;
				var system_name = data.system_name;
				var steppy = data.step;
				loadChart(min_temp_graph,max_temp_graph,the_data,precipitation_max,precipitation_step,steppy,system_standards,system_name);
			}
		});

	});
	var min_temp_graph = 20;
	var max_temp_graph = 90;
	var the_data = '[{"Month": "Jan", "Low":27, "High":42, "Precipitation": 3.03},{"Month": "Feb", "Low":28, "High":44, "Precipitation": 2.48},{"Month": "Mar", "Low":35, "High":53, "Precipitation": 3.23},{"Month": "Apr", "Low":44, "High":64, "Precipitation": 3.15},{"Month": "May", "Low":54, "High":75, "Precipitation": 4.13},{"Month": "Jun", "Low":63, "High":83, "Precipitation": 3.23},{"Month": "Jul", "Low":68, "High":87, "Precipitation": 4.13},{"Month": "Aug", "Low":66, "High":84, "Precipitation": 4.88},{"Month": "Sep", "Low":59, "High":78, "Precipitation": 3.82},{"Month": "Oct", "Low":48, "High":67, "Precipitation": 3.07},{"Month": "Nov", "Low":38, "High":55, "Precipitation": 2.83},{"Month": "Dec", "Low":29, "High":45, "Precipitation": 2.8}]';
	var precipitation_max = 5;
	var precipitation_step = 1;

	var steppy = 20;
	var system_standards = "°F";
	var system_name = "american";
    var chart1;

	loadChart(min_temp_graph,max_temp_graph,the_data,precipitation_max,precipitation_step,steppy,system_standards,system_name);
    function loadChart(min_temp_graph,max_temp_graph,the_data,precipitation_max,precipitation_step,steppy,system_standards,system_name)
    {
            chart1 = new cfx.Chart();
            chart1.getData().setSeries(3);
			chart1.setBackground(null);

			/* Temperature */
           	chart1.getAxisY().setMin(min_temp_graph); //Low
           	chart1.getAxisY().setMax(max_temp_graph); // High
		   	chart1.getAxisY().setStep(10);
			if(system_name == "american")
			{
				chart1.getAxisY().getLabels().setItem(0,"20°F");chart1.getAxisY().getLabels().setItem(20,"40°F");chart1.getAxisY().getLabels().setItem(40,"60°F");chart1.getAxisY().getLabels().setItem(60,"80°F");			}
			if(system_name == "metric")
			{
				chart1.getAxisY().getLabels().setItem(0,"-10°C");chart1.getAxisY().getLabels().setItem(10,"0°C");chart1.getAxisY().getLabels().setItem(20,"10°C");chart1.getAxisY().getLabels().setItem(30,"20°C");chart1.getAxisY().getLabels().setItem(40,"30°C");chart1.getAxisY().getLabels().setItem(50,"40°C");			}
			/* Precipitation */
			chart1.getAxisY2().setMin(0);
            chart1.getAxisY2().setMax(precipitation_max);
			chart1.getAxisY2().setStep(precipitation_step);
			if(system_name == "american")
			{
			  chart1.getAxisY2().getLabels().setItem(0,"0inch");chart1.getAxisY2().getLabels().setItem(1,"1inch");chart1.getAxisY2().getLabels().setItem(2,"2inch");chart1.getAxisY2().getLabels().setItem(3,"3inch");chart1.getAxisY2().getLabels().setItem(4,"4inch");chart1.getAxisY2().getLabels().setItem(5,"5inch");			}
			if(system_name == "metric")
			{
			  chart1.getAxisY2().getLabels().setItem(0,"0mm");chart1.getAxisY2().getLabels().setItem(20,"20mm");chart1.getAxisY2().getLabels().setItem(40,"40mm");chart1.getAxisY2().getLabels().setItem(60,"60mm");chart1.getAxisY2().getLabels().setItem(80,"80mm");chart1.getAxisY2().getLabels().setItem(100,"100mm");chart1.getAxisY2().getLabels().setItem(120,"120mm");chart1.getAxisY2().getLabels().setItem(140,"140mm");			}
            var series1 = chart1.getSeries().getItem(0);
            var series2 = chart1.getSeries().getItem(1);
			var series3 = chart1.getSeries().getItem(2);

			/* Second Y-Axis - Precipitation */
			series3.setAxisY(chart1.getAxisY2());
            series1.setGallery(cfx.Gallery.Lines);
			series2.setGallery(cfx.Gallery.Lines);
            series3.setGallery(cfx.Gallery.Bar);
			chart1.getLegendBox().setDock(cfx.DockArea.Bottom);
			chart1.getAllSeries().setMarkerShape(cfx.MarkerShape.None);
			/* Climate Data */
            var data = JSON.parse(the_data);

            chart1.setDataSource(data);
            var divHolder = document.getElementById('ChartDiv');
        	chart1.create(divHolder);
      }
});
       </script>
       <script async="" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js">
       </script>
       <script>
        (adsbygoogle = window.adsbygoogle || []).push({
          google_ad_client: "ca-pub-9519329606981542",
          enable_page_level_ads: true
     });
       </script>
      </meta>
     </meta>
    </meta>
   </link>
  </link>
 </head>
 <body>
  <script>
   (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-2018376-13', 'auto');
  ga('send', 'pageview');
  </script>
  <!-- Start header **** -->
  <header>
   <!-- Wrap -->
   <div class="wrap">
    <!-- Logo & Slogan -->
    <div id="logo">
     <!-- Slogan -->
     <div id="slogan">
      <h1>
       Temperature - Precipitation - Sunshine - Snowfall
      </h1>
     </div>
     <!-- End slogan -->
    </div>
    <!-- End Logo & Slogan -->
    <!-- Social media -->
    <div id="sociale-media">
     <div id="scale">
      <span class="sociale-media-text">
       US Climate Data on
      </span>
      <a href="https://www.facebook.com/yourweatherservice" title="US Climate Data on Facebook">
       <img alt="US Climate Data on Facebook" height="16" src="/images/icons/facebook.png" width="16"/>
      </a>
      <a href="https://twitter.com/usclimatedata" title="US Climate Data on Twitter">
       <img alt="US Climate Data on Twitter" height="16" src="/images/icons/twitter.png" width="16"/>
      </a>
     </div>
    </div>
   </div>
   <!-- End wrap -->
  </header>
  <!-- End header **** -->
  <!-- Navigation **** -->
  <nav>
   <div class="wrapper_menu_full menu_light_theme">
    <!-- Begin menu wrapper -->
    <div class="menu menu_blue">
     <!-- Begin menu -->
     <div class="wrap">
      <ul class="menu_whole_width">
       <!-- Home -->
       <li class="nodrop">
        <a href="http://www.usclimatedata.com" title="Climate">
         Home
        </a>
       </li>
       <!-- United States -->
       <li class="nodrop">
        <a href="/climate/united-states/us" title="Climate United States">
         United States
        </a>
       </li>
       <!-- World -->
       <!--
            <li><a title="Climate of the World" href="#" class="drop">World</a>
            -->
       <!-- Subitems -->
       <!--
            	<div class="dropdown_1column">
                    <div class="col_1 firstcolumn">
                        <ul class="levels">
                            <li><a title="Climate Africa" href="/normals/africa/2">Africa</a></li>
                            <li><a title="Climate Asia" href="/normals/asia/142">Asia</a></li>
                            <li><a title="Climate Europe" href="/normals/europe/150">Europe</a></li>
                            <li><a title="Climate North-Central America" href="/normals/north-central-america/19">North-Central America</a></li>
                            <li><a title="Climate South America" href="/normals/south-america/20">South America</a></li>
                            <li><a title="Climate Oceania" href="/normals/oceania/9">Oceania</a></li>
                        </ul>
                    </div>
                </div>
                -->
      </ul>
     </div>
    </div>
   </div>
  </nav>
 </body>
</html>
<div id="search">
 <input class="form-text" id="searchfield" value="Enter a location"/>
</div>
<!-- My location -->
<!-- End navigation **** -->
<!-- Content **** -->
<div id="content">
 <!-- Wrap -->
 <div class="wrap">
  <!-- Climate -->
  <div id="climate">
   <!-- Site Tabs -->
   <div class="site_tabs">
    <!-- Tabs -->
    <div id="tabs">
     <ul>
      <li>
       <a class="summary" href="#summary">
        Monthly
       </a>
      </li>
      <!-- Breadcrumbs -->
      <p class="breadcrumbs">
       You are here:
       <a href="\" title="Home">
        Home
       </a>
      </p>
      <!-- end Breadcrumbs -->
     </ul>
     <!-- Summary -->
     <div id="summary">
      <!-- left_column -->
      <div class="left_column">
       <h1 class="h1_title">
        Climate Washington - District of Columbia
       </h1>
       <span class="choose_system">
        <a class="btn" href="#" id="metric" rel="nofollow">
         °C
        </a>
        |
        <a class="btn" href="#" id="american" rel="nofollow">
         °F
        </a>
       </span>
       <!-- Climate table -->
       <div id="climate_table">
        <table>
         <tr>
          <th>
          </th>
          <th class="climate_table_data_td">
           Jan
          </th>
          <th class="climate_table_data_td">
           Feb
          </th>
          <th class="climate_table_data_td">
           Mar
          </th>
          <th class="climate_table_data_td">
           Apr
          </th>
          <th class="climate_table_data_td">
           May
          </th>
          <th class="climate_table_data_td">
           Jun
          </th>
         </tr>
         <tr>
          <td class="climate_table_info">
           Average high in
           <span class="system">
           </span>
           :
          </td>
          <td class="align_right temperature_red">
           42
          </td>
          <td class="align_right temperature_red">
           44
          </td>
          <td class="align_right temperature_red">
           53
          </td>
          <td class="align_right temperature_red">
           64
          </td>
          <td class="align_right temperature_red">
           75
          </td>
          <td class="align_right temperature_red">
           83
          </td>
         </tr>
         <tr>
          <td class="climate_table_info">
           Average low in
           <span class="system">
           </span>
           :
          </td>
          <td class="align_right temperature_blue">
           27
          </td>
          <td class="align_right temperature_blue">
           28
          </td>
          <td class="align_right temperature_blue">
           35
          </td>
          <td class="align_right temperature_blue">
           44
          </td>
          <td class="align_right temperature_blue">
           54
          </td>
          <td class="align_right temperature_blue">
           63
          </td>
         </tr>
         <tr>
          <td class="climate_table_info">
           Av. precipitation in
           <span class="precip_system">
           </span>
           :
          </td>
          <td class="align_right">
           3.03
          </td>
          <td class="align_right">
           2.48
          </td>
          <td class="align_right">
           3.23
          </td>
          <td class="align_right">
           3.15
          </td>
          <td class="align_right">
           4.13
          </td>
          <td class="align_right">
           3.23
          </td>
         </tr>
         <tr>
          <td class="climate_table_info">
           Days with precipitation:
          </td>
          <td class="align_right">
           11
          </td>
          <td class="align_right">
           8
          </td>
          <td class="align_right">
           12
          </td>
          <td class="align_right">
           10
          </td>
          <td class="align_right">
           12
          </td>
          <td class="align_right">
           9
          </td>
         </tr>
         <tr>
          <td class="climate_table_info">
           Hours of sunshine:
          </td>
          <td class="align_right">
           76
          </td>
          <td class="align_right">
           97
          </td>
          <td class="align_right">
           135
          </td>
          <td class="align_right">
           182
          </td>
          <td class="align_right">
           221
          </td>
          <td class="align_right">
           214
          </td>
         </tr>
        </table>
        <table class="climate_table_margin_top">
         <tr>
          <th>
          </th>
          <th class="climate_table_data_td">
           Jul
          </th>
          <th class="climate_table_data_td">
           Aug
          </th>
          <th class="climate_table_data_td">
           Sep
          </th>
          <th class="climate_table_data_td">
           Oct
          </th>
          <th class="climate_table_data_td">
           Nov
          </th>
          <th class="climate_table_data_td">
           Dec
          </th>
         </tr>
         <tr>
          <td class="climate_table_info">
           Average high in
           <span class="system">
           </span>
           :
          </td>
          <td class="align_right temperature_red">
           87
          </td>
          <td class="align_right temperature_red">
           84
          </td>
          <td class="align_right temperature_red">
           78
          </td>
          <td class="align_right temperature_red">
           67
          </td>
          <td class="align_right temperature_red">
           55
          </td>
          <td class="align_right temperature_red">
           45
          </td>
         </tr>
         <tr>
          <td class="climate_table_info">
           Average low in
           <span class="system">
           </span>
           :
          </td>
          <td class="align_right temperature_blue">
           68
          </td>
          <td class="align_right temperature_blue">
           66
          </td>
          <td class="align_right temperature_blue">
           59
          </td>
          <td class="align_right temperature_blue">
           48
          </td>
          <td class="align_right temperature_blue">
           38
          </td>
          <td class="align_right temperature_blue">
           29
          </td>
         </tr>
         <tr>
          <td class="climate_table_info">
           Av. precipitation in
           <span class="precip_system">
           </span>
           :
          </td>
          <td class="align_right">
           4.13
          </td>
          <td class="align_right">
           4.88
          </td>
          <td class="align_right">
           3.82
          </td>
          <td class="align_right">
           3.07
          </td>
          <td class="align_right">
           2.83
          </td>
          <td class="align_right">
           2.8
          </td>
         </tr>
         <tr>
          <td class="climate_table_info">
           Days with precipitation:
          </td>
          <td class="align_right">
           10
          </td>
          <td class="align_right">
           10
          </td>
          <td class="align_right">
           8
          </td>
          <td class="align_right">
           8
          </td>
          <td class="align_right">
           8
          </td>
          <td class="align_right">
           9
          </td>
         </tr>
         <tr>
          <td class="climate_table_info">
           Hours of sunshine:
          </td>
          <td class="align_right">
           226
          </td>
          <td class="align_right">
           186
          </td>
          <td class="align_right">
           170
          </td>
          <td class="align_right">
           123
          </td>
          <td class="align_right">
           87
          </td>
          <td class="align_right">
           66
          </td>
         </tr>
        </table>
       </div>
       <!-- end Climate table -->
       <!-- Google Ad Content Left -->
       <div id="google-ad-content_left">
        <p style="padding-top:4px">
         <script async="" src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js">
         </script>
         <!-- Weernetwerk2012Content -->
         <ins class="adsbygoogle" data-ad-client="ca-pub-9519329606981542" data-ad-slot="4359484752" style="display:inline-block;width:468px;height:60px">
         </ins>
         <script>

In [18]:
my_table_top = soup.find('table')
# print(my_table1.prettify())

In [19]:
td_top = my_table_top.findAll('td')
td_top

[<td class="climate_table_info">Average high in <span class="system"></span>:</td>,
 <td class="align_right temperature_red">42</td>,
 <td class="align_right temperature_red">44</td>,
 <td class="align_right temperature_red">53</td>,
 <td class="align_right temperature_red">64</td>,
 <td class="align_right temperature_red">75</td>,
 <td class="align_right temperature_red">83</td>,
 <td class="climate_table_info">Average low in <span class="system"></span>:</td>,
 <td class="align_right temperature_blue">27</td>,
 <td class="align_right temperature_blue">28</td>,
 <td class="align_right temperature_blue">35</td>,
 <td class="align_right temperature_blue">44</td>,
 <td class="align_right temperature_blue">54</td>,
 <td class="align_right temperature_blue">63</td>,
 <td class="climate_table_info">Av. precipitation in <span class="precip_system"></span>:</td>,
 <td class="align_right">3.03</td>,
 <td class="align_right">2.48</td>,
 <td class="align_right">3.23</td>,
 <td class="align_right">3.15</td>,
 <td class="align_right">4.13</td>,
 <td class="align_right">3.23</td>,
 <td class="climate_table_info">Days with precipitation:</td>,
 <td class="align_right">11</td>,
 <td class="align_right">8</td>,
 <td class="align_right">12</td>,
 <td class="align_right">10</td>,
 <td class="align_right">12</td>,
 <td class="align_right">9</td>,
 <td class="climate_table_info">Hours of sunshine:</td>,
 <td class="align_right">76</td>,
 <td class="align_right">97</td>,
 <td class="align_right">135</td>,
 <td class="align_right">182</td>,
 <td class="align_right">221</td>,
 <td class="align_right">214</td>]

In [20]:
my_table_bottom = soup.find('table', {'class':'climate_table_margin_top'})

In [21]:
td_bottom = my_table_bottom.findAll('td')

In [22]:
temps = []

In [23]:
temps_high = []
temps_low = []

In [24]:
for row in range(1, 7):
    print(int(re.findall('\d+', str(td_top[row]))[0]))
    temps_high.append(int(re.findall('\d+', str(td_top[row]))[0]))
print(temps_high)

42
44
53
64
75
83
[42, 44, 53, 64, 75, 83]

In [25]:
for row in range(8, 14):
    print(int(re.findall('\d+', str(td_top[row]))[0]))
    temps_low.append(int(re.findall('\d+', str(td_top[row]))[0]))
print(temps_low)

27
28
35
44
54
63
[27, 28, 35, 44, 54, 63]

In [26]:
for row in range(1, 7):
    print(int(re.findall('\d+', str(td_bottom[row]))[0]))
    temps_high.append(int(re.findall('\d+', str(td_bottom[row]))[0]))
print(temps_high)

87
84
78
67
55
45
[42, 44, 53, 64, 75, 83, 87, 84, 78, 67, 55, 45]

In [27]:
for row in range(8, 14):
    print(int(re.findall('\d+', str(td_bottom[row]))[0]))
    temps_low.append(int(re.findall('\d+', str(td_bottom[row]))[0]))
print(temps_low)

68
66
59
48
38
29
[27, 28, 35, 44, 54, 63, 68, 66, 59, 48, 38, 29]

In [28]:
temps.append(temps_low)
temps.append(temps_high)

In [29]:
df = pd.DataFrame(temps).T
df.head()

    0   1
0  27  42
1  28  44
2  35  53
3  44  64
4  54  75

Odtąd próbuję stworzyć listę podstron dla wszystkich stanów USA

In [46]:
# for link in soup.findAll('a', attrs={'href': re.compile("^http://")}):
#     print(link.get('href'))

In [48]:
# 'href': re.compile("^http://")

In [52]:
'https://www.usclimatedata.com//climate/'[38]

'/'

In [56]:
upper('abc')

NameError: name 'upper' is not defined

In [66]:
re.findall('^.+climate/(.+)/united.+','https://www.usclimatedata.com/climate/alabama/united-states/3170')

['alabama']

In [75]:
for link in soup.findAll('a', {'class': 'province'}):
    print(f"{url}{link.get('href')}", re.findall('^.+climate/(.+)/united.+', f'{url}{link.get("href")}')[0].capitalize())

https://www.usclimatedata.com/climate/alabama/united-states/3170 Alabama
https://www.usclimatedata.com/climate/kentucky/united-states/3187 Kentucky
https://www.usclimatedata.com/climate/north-dakota/united-states/3204 North-dakota
https://www.usclimatedata.com/climate/alaska/united-states/3171 Alaska
https://www.usclimatedata.com/climate/louisiana/united-states/3188 Louisiana
https://www.usclimatedata.com/climate/ohio/united-states/3205 Ohio
https://www.usclimatedata.com/climate/arizona/united-states/3172 Arizona
https://www.usclimatedata.com/climate/maine/united-states/3189 Maine
https://www.usclimatedata.com/climate/oklahoma/united-states/3206 Oklahoma
https://www.usclimatedata.com/climate/arkansas/united-states/3173 Arkansas
https://www.usclimatedata.com/climate/maryland/united-states/1872 Maryland
https://www.usclimatedata.com/climate/oregon/united-states/3207 Oregon
https://www.usclimatedata.com/climate/california/united-states/3174 California
https://www.usclimatedata.com/climate/massachusetts/united-states/3191 Massachusetts
https://www.usclimatedata.com/climate/pennsylvania/united-states/3208 Pennsylvania
https://www.usclimatedata.com/climate/colorado/united-states/3175 Colorado
https://www.usclimatedata.com/climate/michigan/united-states/3192 Michigan
https://www.usclimatedata.com/climate/rhode-island/united-states/3209 Rhode-island
https://www.usclimatedata.com/climate/connecticut/united-states/3176 Connecticut
https://www.usclimatedata.com/climate/minnesota/united-states/3193 Minnesota
https://www.usclimatedata.com/climate/south-carolina/united-states/3210 South-carolina
https://www.usclimatedata.com/climate/delaware/united-states/3177 Delaware
https://www.usclimatedata.com/climate/mississippi/united-states/3194 Mississippi
https://www.usclimatedata.com/climate/south-dakota/united-states/3211 South-dakota
https://www.usclimatedata.com/climate/district-of-columbia/united-states/3178 District-of-columbia
https://www.usclimatedata.com/climate/missouri/united-states/3195 Missouri
https://www.usclimatedata.com/climate/tennessee/united-states/3212 Tennessee
https://www.usclimatedata.com/climate/florida/united-states/3179 Florida
https://www.usclimatedata.com/climate/montana/united-states/919 Montana
https://www.usclimatedata.com/climate/texas/united-states/3213 Texas
https://www.usclimatedata.com/climate/georgia/united-states/3180 Georgia
https://www.usclimatedata.com/climate/nebraska/united-states/3197 Nebraska
https://www.usclimatedata.com/climate/utah/united-states/3214 Utah
https://www.usclimatedata.com/climate/hawaii/united-states/3181 Hawaii
https://www.usclimatedata.com/climate/nevada/united-states/3198 Nevada
https://www.usclimatedata.com/climate/vermont/united-states/3215 Vermont
https://www.usclimatedata.com/climate/idaho/united-states/3182 Idaho
https://www.usclimatedata.com/climate/new-hampshire/united-states/3199 New-hampshire
https://www.usclimatedata.com/climate/virginia/united-states/3216 Virginia
https://www.usclimatedata.com/climate/illinois/united-states/3183 Illinois
https://www.usclimatedata.com/climate/new-jersey/united-states/3200 New-jersey
https://www.usclimatedata.com/climate/washington/united-states/3217 Washington
https://www.usclimatedata.com/climate/indiana/united-states/3184 Indiana
https://www.usclimatedata.com/climate/new-mexico/united-states/3201 New-mexico
https://www.usclimatedata.com/climate/west-virginia/united-states/3218 West-virginia
https://www.usclimatedata.com/climate/iowa/united-states/3185 Iowa
https://www.usclimatedata.com/climate/new-york/united-states/3202 New-york
https://www.usclimatedata.com/climate/wisconsin/united-states/3219 Wisconsin
https://www.usclimatedata.com/climate/kansas/united-states/3186 Kansas
https://www.usclimatedata.com/climate/north-carolina/united-states/3203 North-carolina
https://www.usclimatedata.com/climate/wyoming/united-states/3220 Wyoming

Od tego miejsca próbuję ustawić odpowiedni indeks, żeby móc później dokleić temps do dataframe'a

In [244]:
df.columns =['low_temp', 'high_temp']

In [245]:
df

    low_temp  high_temp
0         27         42
1         28         44
2         35         53
3         44         64
4         54         75
5         63         83
6         68         87
7         66         84
8         59         78
9         48         67
10        38         55
11        29         45

In [264]:
# mies =[]
# for month in calendar.month_name[1:]:
#     mies.append(month)
# print(mies)

['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']

In [269]:
# df.index =mies
# df

In [291]:
df.index = pd.date_range(start ='2010-01-01', 
              end ='2010-12-01',
              freq ='MS')

In [292]:
df

            low_temp  high_temp
2010-01-01        27         42
2010-02-01        28         44
2010-03-01        35         53
2010-04-01        44         64
2010-05-01        54         75
2010-06-01        63         83
2010-07-01        68         87
2010-08-01        66         84
2010-09-01        59         78
2010-10-01        48         67
2010-11-01        38         55
2010-12-01        29         45

In [286]:
pd.concat([df,df])

           low_temp  high_temp
January          27         42
February         28         44
March            35         53
April            44         64
May              54         75
June             63         83
July             68         87
August           66         84
September        59         78
October          48         67
November         38         55
December         29         45
January          27         42
February         28         44
March            35         53
April            44         64
May              54         75
June             63         83
July             68         87
August           66         84
September        59         78
October          48         67
November         38         55
December         29         45